### ISSUE TITLE
I can't get Toggler to show up in Nova4  Laravel 10.30.0

### ISSUE THREAD

**Issue by mayking0811** [dcasia/column-toggler#16]
Hi,

I am using Laravel 10.30.0, and Toggler does not show up in Nova4. Can you take a look? Thank you very much

**Comment by milewski** [comment]
It is probably due to some other packages you might have installed that override some native nova components instead of extending it.. can you post your composer.json so I can tell you which one is causing trouble?

**Comment by mayking0811** [comment]
Thank you very much to look into this problem. Here is my composer.json:


    "require": {

        "php": "^8.2.7",

        "ext-exif": "*",

        "ably/ably-php": "^1.1",

        "alexwenzel/nova-dependency-container": "^1.7",

        "appstract/laravel-meta": "^2.0",

        "aws/aws-sdk-php": "^3.224",

        "babenkoivan/elastic-client": "^2.1",

        "babenkoivan/elastic-migrations": "^3.4",

        "babenkoivan/elastic-scout-driver": "^3.1",

        "babenkoivan/elastic-scout-driver-plus": "^4.6.0",

        "barryvdh/laravel-debugbar": "^3.7",

        "barryvdh/laravel-dompdf": "^2.0",

        "blendbyte/nova-items-field": "^1.2",

        "braintree/braintree_php": "^6.8",

        "cloudstudio/card-extended": "dev-master",

        "codebar-ag/laravel-prerender": "^3.3.0",

        "coroowicaksono/chart-js-integration": "0.3",

        "digital-creative/column-toggler": "^0.1.1",

        "dmitrybubyakin/nova-medialibrary-field": "^4.0",

        "ebess/advanced-nova-media-library": "^4.0",

        "eminiarts/nova-tabs": "^2.0",

        "guzzlehttp/guzzle": "^7.2",

        "illuminate/console": "^10.0",

        "illuminate/contracts": "^10.0",

        "illuminate/support": "^10.0",

        "inertiajs/inertia-laravel": "^0.6.2",

        "interaction-design-foundation/nova-html-card": "^3.1",

        "intonate/laravel-mandrill-driver": "^3.0",

        "kabbouchi/nova-impersonate": "^2.0",

        "khalin/nova-link-field": "^1.2",

        "kiritokatklian/nova-permission": "^4.0",

        "lab404/laravel-impersonate": "^1.7",

        "laravel/fortify": "^1.13",

        "laravel/framework": "^10.0",

        "laravel/jetstream": "^2.8",

        "laravel/legacy-factories": "^1.3",

        "laravel/nova": "~4.5",

        "laravel/octane": "^2.1",

        "laravel/passport": "^11.0",

        "laravel/sanctum": "^3.2",

        "laravel/scout": "^10.5",

        "laravel/slack-notification-channel": "^2.4",

        "laravel/telescope": "^4.9",

        "laravel/tinker": "^2.7",

        "laravel/ui": "^4.0",

        "laravel/vapor-cli": "^1.60",

        "laravel/vapor-core": "^2.33",

        "laravel/vapor-ui": "^1.7",

        "laravel/vonage-notification-channel": "^3.0",

        "league/flysystem-aws-s3-v3": "^3.0",

        "maatwebsite/excel": "^3.1",

        "maatwebsite/laravel-nova-excel": "^1.3",

        "mailchimp/marketing": "^3.0",

        "manogi/nova-tiptap": "^3.2",

        "nibri10/nova-grid": "^1.0",

        "nova-kit/nova-on-vapor": "^1.1",

        "outl1ne/nova-notes-field": "^3.0",

        "owen-it/laravel-auditing": "^13.0",

        "predis/predis": "^2.0",

        "psr/simple-cache": "^2.0",

        "pusher/pusher-php-server": "^7.0",

        "rimu/formatted-number": "^0.2.0",

        "saumini/count": "^1.0",

        "setasign/fpdf": "^1.8",

        "setasign/fpdi": "^2.3",

        "shippo/shippo-php": "^2.0",

        "sloveniangooner/searchable-select": "^1.3",

        "spatie/data-transfer-object": "^3.8",

        "spatie/laravel-collection-macros": "^7.11",

        "spatie/laravel-csp": "^2.7",

        "spatie/laravel-medialibrary": "^10.3",

        "spatie/laravel-medialibrary-pro": "^2.5",

        "spatie/laravel-permission": "^5.5",

        "spatie/laravel-ray": "^1.29",

        "spatie/laravel-robots-middleware": "^1.3",

        "spatie/laravel-schemaless-attributes": "^2.3",

        "staudenmeir/eloquent-json-relations": "^1.1",

        "stepanenko3/nova-command-runner": "~4.0",

        "storyblok/php-client": "^2.6.0",

        "symfony/mailer": "^6.1",

        "tightenco/ziggy": "^1.4",

        "titasgailius/search-relations": "^2.0",

        "wdelfuego/nova-calendar": "^1.6",

        "whitecube/nova-flexible-content": "*"

    },

    "require-dev": {

        "fakerphp/faker": "^1.9.1",

        "laracasts/generators": "^2.0.1",

        "laravel/dusk": "^7.0",

        "laravel/sail": "^1.0.1",

        "mockery/mockery": "^1.4.4",

        "nunomaduro/collision": "^7.0",

        "phpunit/phpunit": "^10.0",

        "spatie/laravel-ignition": "^2.3"

    },

**Comment by milewski** [comment]
I couldn't identify any of these packages as being the root cause, did you add the column toggler trait to your resource?

**Comment by mayking0811** [comment]
Sorry, after I upgrade to v0.2.0, this package is working again. Thank you for the help!
