### ISSUE TITLE
No issue.

### ISSUE THREAD

**Issue by philipbaginski** [dcasia/column-toggler#24]
Hi!

There is no other place to write it, so I will do it here: column sorting is one of the greatest function of this package!

Keep coding :-)

**Comment by milewski** [comment]
Ahah thanks! I hope one day if this feature is built in nova the sorting is also included!

**Comment by omastroberti** [comment]
Hello, no issue here either, but I wanna know which version is compatible with Nova 3. Thanks

**Comment by milewski** [comment]
Hey this package was created for nova 4 only.. there is no version compatible with Nova 3
