### ISSUE TITLE
Bug that automatically hides all columns for relationships that are not also in the owner model

### ISSUE THREAD

**Issue by AndrewMast** [dcasia/column-toggler#4]
First off, I'm glad that you created this package! Being able to hide columns (and by default!) is amazing.

The package works as expected on index pages, but on any relationship, most of the columns are hidden by default. Take a look at this gif:
![column-toggler](https://github.com/dcasia/column-toggler/assets/13026511/f48b495d-061d-4f09-8f20-7d9e33e26153)

You can see when I refresh the page, I see all of my columns for an instant and then it starts hiding them until I am left with columns that are both in the parent model and the relationship's model. I was able to track down this error to the `ColumnTogglerTrait.php` file on lines 43-45 where the fields are filtered by the `columnToggler` request array. This array contains a list of the parent model's enabled columns, not the relationship's columns. Because I only have the `ID` and `UID` columns in common between most of my relationships, I can only see those two columns. I have been able to see additional columns (ie "languages") when both the main model and the model of its relation have that column.

Due to this bug, I won't be able to use this package, but when this gets fixed, I will definitely give it another try!

**Comment by milewski** [comment]
Hi, I'm unable to reproduce this, can you tell me what other packages you have installed? what type of relationship it is?

**Comment by AndrewMast** [comment]
The bug happens with both native nova fields and fields from packages. I have even removed all package-based fields with the same results.
Edit: It's a normal `HasMany` relationship.

**Comment by milewski** [comment]
This is how I'm testing, I have a table `Users` and `Articles` User Has Many Articles, on the user details page I show the articles' relationship and it is working:

![image](https://github.com/dcasia/column-toggler/assets/2874967/05f00c5b-088a-4ca6-aea3-57af33c2c107)

**Comment by AndrewMast** [comment]
It works when I go in and actually toggle a column. When I leave everything enabled by default, it then messes up.

**Comment by milewski** [comment]
What happens when you clear your localstorage cache, then refresh the page?

Can you send a screenshot of how you localstorage looks like after the refresh:

![image](https://github.com/dcasia/column-toggler/assets/2874967/04b33c95-cf9e-4337-acb9-d1f60b0fe2ef)

**Comment by AndrewMast** [comment]
Localstorage does nothing. Ah! Have you tried it when you have multiple relationships?

**Comment by AndrewMast** [comment]
When having two relationships, the first relationship (in order from top to bottom) has all of the fields when it first loads, and then narrows down to only show the fields that are also in the second relationship. When having even more relationships, the fields for all above relationships are filtered as well.

**Comment by AndrewMast** [comment]
I have uninstalled all nova packages, and nothing changes anything. I am only able to properly use the `column-toggler` package when I only have one relationship on a model.

**Comment by AndrewMast** [comment]
![image](https://github.com/dcasia/column-toggler/assets/13026511/b4fbf37f-9c68-4fac-ada3-3d87e5bd36e1)
By commenting out what columns the nova resource for model 2 has, I am able to remove columns from model 1. Checking and unchecking any column from the toggle menu shows the expected result.

![image](https://github.com/dcasia/column-toggler/assets/13026511/d4c3250e-2353-40d2-bef6-faad4b1974d5)

**Comment by milewski** [comment]
Okay got it, working on a fix now

**Comment by AndrewMast** [comment]
Thank you! I'm glad you were able to reproduce it.

**Comment by milewski** [comment]
Fixed here: https://github.com/dcasia/column-toggler/pull/5
